from collections import OrderedDict
DEFAULT_CONFIG = OrderedDict({
"a_core_diameter": 0.2,
"b_core_diameter": 0.2,
"a_core_repulsion": 2.0,
"b_core_repulsion": 2.0,
"chromatin_bond_spring": 0.1,
"chromatin_bond_length": 0.2,
"chromatin_mobility": 1.0,
"a_core_bond_spring": 0.0,
"a_core_bond_length": 0.0,
"b_core_bond_spring": 0.0,
"b_core_bond_length": 0.0,
"a_core_2nd_bond_spring": 0.0,
"b_core_2nd_bond_spring": 0.0,
"nucleolus_sidebeads": 2,
"nucleolus_a_factor": 5,
"nucleolus_b_factor": 5,
"nucleolus_bond_spring": 5.0,
"nucleolus_bond_length": 0.0,
"nucleolus_droplet_energy": 0.0,
"nucleolus_droplet_decay": 0.2,
"nucleolus_droplet_cutoff": 0.4,
"nucleolus_mobility": 1.0,
"wall_init_semiaxes": [1.0, 1.0, 1.0],
"wall_semiaxes_spring": [1.0e4, 1.0e4, 1.0e4],
"wall_packing_spring": 5000,
"wall_a_factor": 5,
"wall_b_factor": 5,
"wall_mobility": 1.0e-4,
"bead_scale_init": 1.0,
"bead_scale_tau": 1.0,
"bond_scale_init": 1.0,
"bond_scale_tau": 1.0,
"init_coarse_graining": 100,
"init_bead_diameter": 0.2,
"init_bead_repulsion": 5.0,
"init_bond_length": 0.2,
"init_bond_spring": 500.0,
"init_bend_energy": 0.0,
"init_spindle_spring": 1.0,
"init_spindle_point": [0, 0, 0],
"init_packing_radius": 1.0,
"init_packing_spring": 0.0,
"init_start_point": [5, 0, 0],
"init_start_stddev": 1.0,
"init_mobility": 1.0,
"init_temperature": 0.1,
"init_timestep": 1e-4,
"init_spacestep": 0,
"init_spindle_steps": 10000,
"init_packing_steps": 10000,
"init_sampling_interval": 1000,
"init_logging_interval": 1000,
"init_refinement_method": "spline",
"relaxation_temperature": 1.0,
"relaxation_timestep": 1.0e-5,
"relaxation_spacestep": 0,
"relaxation_steps": 10000,
"relaxation_sampling_interval": 100,
"relaxation_logging_interval": 100,
"interphase_temperature": 1.0,
"interphase_timestep": 1e-5,
"interphase_spacestep": 0,
"interphase_steps": 10000,
"interphase_sampling_interval": 1000,
"interphase_logging_interval": 100,
"contactmap_distance": 0.4,
"contactmap_update_interval": 100,
"contactmap_thinning_rate": 100,
"spindle_seed": 0,
"interphase_seed": 0,
})
